#!/bin/bash

DOTFILES_DIRECTORY="${HOME}/dotfiles"

link() {
    # Force create/replace the symlink.
    ln -fs "${DOTFILES_DIRECTORY}/${1}" "${HOME}/${2}"
}

createLinks() {
    link "bash/bashrc" ".bashrc"
    link "bash/bash_profile" ".bash_profile"
    link "bash/bash_aliases" ".bash_aliases"
    link "bash/bash_env" ".bash_env"
    link "bash/bash_path" ".bash_path"
}

createLinks